# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: /bin/zsh
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/michal/dev/oh-my-git-aliases
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 87
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 20
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: auto
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: floating
    title: oh-my-git-aliases 
    style:
      border: 0px black solid
      # boxShadow: none
      # margin: 0px
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#ffffff"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#ffffff"
  
# Records, feel free to edit them
records:
  - delay: 0
    content: "\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a\e]1337;ShellIntegrationVersion=6;shell=zsh\a"
  - delay: 197
    content: "\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 43
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mmaster\e[34m)\e[33m✗\e[00m \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 768
    content: gst
  - delay: 50
    content: "\e[?1l\e>\e[?2004l\r\r\n\e]2;git status\a\e]1;gst\a\e]133;C;\a"
  - delay: 10
    content: "On branch master\r\nYour branch is up to date with 'origin/master'.\r\n\r\nChanges not staged for commit:\r\n  (use \"git add <file>...\" to update what will be committed)\r\n  (use \"git checkout -- <file>...\" to discard changes in working directory)\r\n\r\n\t\e[31mmodified:   README.md\e[m\r\n\r\nno changes added to commit (use \"git add\" and/or \"git commit -a\")\r\n\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 34
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mmaster\e[34m)\e[33m✗\e[00m \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 1464
    content: g
  - delay: 96
    content: "\bgf"
  - delay: 88
    content: "\e[?1l\e>\e[?2004l\r\r\n\e]2;git fetch\a\e]1;gf\a\e]133;C;\a"
  - delay: 1644
    content: "remote: Enumerating objects: 5, done.\e[K\r\nremote: Counting objects:  20% (1/5)   \e[K\rremote: Counting objects:  40% (2/5)   \e[K\rremote: Counting objects:  60% (3/5)   \e[K\rremote: Counting objects:  80% (4/5)   \e[K\rremote: Counting objects: 100% (5/5)   \e[K\rremote: Counting objects: 100% (5/5), done.\e[K\r\nremote: Compressing objects:  33% (1/3)   \e[K\rremote: Compressing objects:  66% (2/3)   \e[K\rremote: Compressing objects: 100% (3/3)   \e[K\rremote: Compressing objects: 100% (3/3), done.\e[K\r\nremote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0\e[K\r\n"
  - delay: 7
    content: "Unpacking objects:  33% (1/3)   \rUnpacking objects:  66% (2/3)   \rUnpacking objects: 100% (3/3)   \rUnpacking objects: 100% (3/3), done.\r\n"
  - delay: 123
    content: "From github.com:mjkonarski/oh-my-git-aliases\r\n   71797a9..ce2771e  master     -> origin/master\r\n"
  - delay: 7
    content: "\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 34
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mmaster\e[34m)\e[33m✗\e[00m \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 621
    content: g
  - delay: 160
    content: "\bgg"
  - delay: 72
    content: r
  - delay: 144
    content: h
  - delay: 160
    content: "\e[?1l\e>\e[?2004l\r\r\n\e]2;git reset --hard origin/$(current_branch)\a\e]1;ggrh\a\e]133;C;\a"
  - delay: 17
    content: "HEAD is now at ce2771e Update README.md\r\n\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 38
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mmaster\e[34m) \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 1262
    content: g
  - delay: 217
    content: "\bgc"
  - delay: 199
    content: o
  - delay: 143
    content: ' '
  - delay: 409
    content: "new_feature"
  - delay: 431
    content: "\e[?1l\e>\e[?2004l\r\r\n\e]2;git checkout new_feature\a\e]1;gco\a\e]133;C;\a"
  - delay: 10
    content: "Switched to branch 'new_feature'\r\n\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 37
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mnew_feature\e[34m) \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 837
    content: g
  - delay: 159
    content: "\bggpush"
  - delay: 281
    content: "\e[?1l\e>\e[?2004l\r\r\n\e]2;git push origin $(current_branch)\a\e]1;ggpush\a\e]133;C;\a"
  - delay: 1000
    content: "Counting objects: 3, done.\r\nDelta compression using up to 4 threads.\r\nCompressing objects:  50% (1/2)   \rCompressing objects: 100% (2/2)   \rCompressing objects: 100% (2/2), done.\r\nWriting objects:  33% (1/3)   \rWriting objects:  66% (2/3)   \rWriting objects: 100% (3/3)   \rWriting objects: 100% (3/3), 285 bytes | 285.00 KiB/s, done.\r\nTotal 3 (delta 1), reused 0 (delta 0)\r\n"
  - delay: 176
    content: "remote: Resolving deltas:   0% (0/1)   \e[K\r"
  - delay: 10
    content: "remote: Resolving deltas: 100% (1/1)   \e[K\rremote: Resolving deltas: 100% (1/1), completed with 1 local object.\e[K\r\n"
  - delay: 1913
    content: "To github.com:mjkonarski/oh-my-git-aliases.git\r\n   8da9f04..07e633f  new_feature -> new_feature\r\n\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r\e]2;michal@askia: ~/dev/oh-my-git-aliases\a\e]1;..y-git-aliases\a\e]133;D;0\a\e]1337;RemoteHost=michal@askia.niceland\a\e]1337;CurrentDir=/Users/michal/dev/oh-my-git-aliases\a"
  - delay: 37
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[01;32mmichal@askia \e[01;34m~/dev/oh-my-git-aliases git:(\e[31mnew_feature\e[34m) \e[00m\r\n\e[01;34m$\e[00m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 2000
    content: ''
